# Generated by Django 3.1.5 on 2021-09-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('degree', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('previus_work', models.TextField()),
                ('skills', models.CharField(max_length=150)),
            ],
        ),
    ]
